# Base Image: Node.js 8.X
FROM node:latest

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
#COPY package*.json ./

#RUN apt-get update
#RUN apt-get install -y python3 python3-dev python3-pip

# Bundle app source
COPY . .
RUN rm -rf node_modules
#RUN pip3 install -r requirements.txt

RUN npm install

#COPY ./ ./app
#WORKDIR ./app

# Expose Port
EXPOSE 3000

# Startup
CMD [ "npm", "start" ]





